"""
Post-processing step for the mdBook output in `.mdbook/book/`.

Created 2026-08-06 after Google Search Console reported the primer's pages under
"Duplicate without user-selected canonical". mdBook emits neither canonical link
tags nor a sitemap, and it copies the first chapter verbatim to `index.html`, so
Google sees `/cpsat-primer/` and `/cpsat-primer/intro.html` as the same page with
no stated preference. This script fills those two gaps.

Run it after `mdbook build`, pointing at the generated book directory:

    python3 .scripts/seo_postprocess.py .mdbook/book --base-url https://d-krupke.github.io/cpsat-primer/

It does three things, all idempotent:

1. injects a `<link rel="canonical">` into every indexable page,
2. points pages that are byte-identical to `index.html` at the site root, so the
   duplicate is consolidated instead of arbitrated by Google,
3. writes `sitemap.xml` and `robots.txt` listing only the canonical URLs.

Redirect stubs (mdBook's `[output.html.redirect]` pages), `print.html` (already
`noindex`) and `404.html` are skipped and kept out of the sitemap.

Change this file when the site moves to a different URL (adjust `--base-url` in
`.github/workflows/deploy.yml`) or when mdBook starts emitting canonical tags of
its own, at which point `insert_canonical` becomes a no-op by design.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path, PurePosixPath
from xml.sax.saxutils import escape

DEFAULT_BASE_URL = "https://d-krupke.github.io/cpsat-primer/"

# Generated by mdBook but never a search result in its own right.
EXCLUDED_PAGES = frozenset({"print.html", "404.html"})


def normalize_base_url(base_url: str) -> str:
    """Return `base_url` with exactly one trailing slash."""
    return base_url.rstrip("/") + "/"


def page_url(base_url: str, rel_path: PurePosixPath) -> str:
    """
    Map a book-relative path to its public URL.

    `index.html` files map to their directory URL, because that is the form
    users and other sites link to (`/cpsat-primer/`, not `/cpsat-primer/index.html`).
    """
    base_url = normalize_base_url(base_url)
    if rel_path.name == "index.html":
        parent = rel_path.parent
        if str(parent) in (".", ""):
            return base_url
        return f"{base_url}{parent}/"
    return f"{base_url}{rel_path}"


def is_rendered_page(html: str) -> bool:
    """
    True for files that are actual rendered documents.

    `src = "."` makes mdBook copy every stray `.html` file in the book source
    through to the output, including Google's site-verification token file, which
    is a single line of text with an `.html` extension. Requiring a `</head>`
    keeps such files out of the sitemap.
    """
    return "</head>" in html


def is_redirect_stub(html: str) -> bool:
    """
    True for the placeholder pages mdBook writes for `[output.html.redirect]`.

    They already carry their own canonical pointing at the redirect target, so
    rewriting them would fight the redirect instead of supporting it.
    """
    return 'http-equiv="refresh"' in html or "http-equiv='refresh'" in html


def is_noindex(html: str) -> bool:
    """True if the page asks robots not to index it (mdBook does this for print.html)."""
    return 'name="robots"' in html and "noindex" in html


def has_canonical(html: str) -> bool:
    """True if a canonical link tag is already present."""
    return 'rel="canonical"' in html or "rel='canonical'" in html


def insert_canonical(html: str, url: str) -> str:
    """
    Insert `<link rel="canonical" href="url">` before `</head>`.

    Returns the input unchanged when a canonical tag already exists (so repeated
    runs are safe) or when there is no `</head>` to anchor the insertion to.
    """
    if has_canonical(html):
        return html
    closing_head = html.find("</head>")
    if closing_head == -1:
        return html
    tag = f'        <link rel="canonical" href="{escape(url, {chr(34): "&quot;"})}">\n'
    return html[:closing_head] + tag + html[closing_head:]


def build_sitemap(urls: list[str]) -> str:
    """Render a minimal urlset sitemap. No `lastmod`: mdBook rebuilds every file
    on every deploy, so file timestamps would claim changes that did not happen."""
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ]
    for url in urls:
        lines.append(f"  <url><loc>{escape(url)}</loc></url>")
    lines.append("</urlset>")
    return "\n".join(lines) + "\n"


def build_robots(sitemap_url: str) -> str:
    """
    Render a permissive robots.txt pointing at the sitemap.

    Note that crawlers only read robots.txt from the *domain* root, so on
    `d-krupke.github.io/cpsat-primer/` this file is informational; the sitemap
    has to be submitted through Search Console. It becomes effective as-is if the
    primer ever moves to its own domain.
    """
    return f"User-agent: *\nAllow: /\n\nSitemap: {sitemap_url}\n"


def _relative_paths(book_dir: Path) -> list[PurePosixPath]:
    """All HTML pages below `book_dir`, as sorted book-relative POSIX paths."""
    return sorted(
        (
            PurePosixPath(p.relative_to(book_dir).as_posix())
            for p in book_dir.rglob("*.html")
        ),
        key=str,
    )


def postprocess(book_dir: Path, base_url: str) -> list[str]:
    """
    Add canonical tags to the built book and write `sitemap.xml` / `robots.txt`.

    Returns the canonical URLs that went into the sitemap. Emits a per-run
    summary on stdout so the deploy log shows whether the page count is sane.
    """
    base_url = normalize_base_url(base_url)
    index_path = book_dir / "index.html"
    index_bytes = index_path.read_bytes() if index_path.is_file() else None

    sitemap_urls: list[str] = []
    skipped_redirects = 0
    skipped_excluded = 0

    for rel_path in _relative_paths(book_dir):
        if str(rel_path) in EXCLUDED_PAGES:
            skipped_excluded += 1
            continue

        path = book_dir / rel_path
        raw = path.read_bytes()
        html = raw.decode("utf-8")

        if is_redirect_stub(html):
            skipped_redirects += 1
            continue
        if is_noindex(html) or not is_rendered_page(html):
            skipped_excluded += 1
            continue

        # mdBook copies the first chapter to index.html verbatim. Point both at
        # the site root rather than letting Google pick a winner.
        is_index_duplicate = (
            index_bytes is not None
            and rel_path.name != "index.html"
            and raw == index_bytes
        )
        canonical = base_url if is_index_duplicate else page_url(base_url, rel_path)

        updated = insert_canonical(html, canonical)
        if updated != html:
            path.write_text(updated, encoding="utf-8")

        if not is_index_duplicate:
            sitemap_urls.append(canonical)

    sitemap_url = f"{base_url}sitemap.xml"
    (book_dir / "sitemap.xml").write_text(build_sitemap(sitemap_urls), encoding="utf-8")
    (book_dir / "robots.txt").write_text(build_robots(sitemap_url), encoding="utf-8")

    print(
        f"seo_postprocess: {len(sitemap_urls)} canonical pages, "
        f"{skipped_redirects} redirect stubs skipped, "
        f"{skipped_excluded} non-indexable pages skipped"
    )
    return sitemap_urls


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    parser.add_argument(
        "book_dir",
        nargs="?",
        default=".mdbook/book",
        type=Path,
        help="directory containing the mdBook output (default: .mdbook/book)",
    )
    parser.add_argument(
        "--base-url",
        default=DEFAULT_BASE_URL,
        help=f"public URL the book is served from (default: {DEFAULT_BASE_URL})",
    )
    args = parser.parse_args(argv)

    if not args.book_dir.is_dir():
        parser.error(f"{args.book_dir} is not a directory - run `mdbook build` first")

    urls = postprocess(args.book_dir, args.base_url)
    if not urls:
        print("seo_postprocess: no indexable pages found", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
